name: Build Updater
on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Build the executable
        run: |
          set -o xtrace
          pyinstaller .\src\main.py -cDF -n updater.windows64 -i .\icon.ico;

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Build Files
          path: updater.windows64

      - name: Create "dist" directory
        run: mkdir -p dist

      - name: Copy output to "build" directory
        run: |
          cp \
          updater.windows64.json \
          dist/

      - name: Update resources
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: dist
            commit-message: Update resources
            branch: data
            clean: false
