name: Build Updater
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86, x64, arm64]
        include:
          - architecture: x86
            build-name: windows-x86
          - architecture: x64
            build-name: windows-x64
          - architecture: arm64
            build-name: windows-x64

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: updater

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "${{ matrix.architecture }}"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Build the executable
        run: |
          pyinstaller .\src\main.py -cDF -n updater.${{ matrix.build-name }} -i .\icon.ico;

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Windows (${{ matrix.architecture }})
          path: dist/updater.${{ matrix.build-name }}.exe

  commit-and-push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: updater

      - uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: updater
          commit_message: Upload new Windows executables
          file_pattern: "dist/*"
